branch-defaults:
  default:
    environment: flask-test7-env
    group_suffix: null
global:
  application_name: flask-test7
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
